services:
  copy:
    build:
      context: https://github.com/oliverbenduhn/copy.git#main
    container_name: copy-app
    environment:
      TIMEOUT: "180"
      GRACEFUL_TIMEOUT: "180"
      SENDFILE: "False"
    volumes:
      - ./transfer:/app/transfer
      - ./slugs.json:/app/slugs.json
    ports:
      - "8089:8089"
